name: anote_tudo
description: Faça suas de compras e ou tarefas do dia e salve em seu celular...
#desenvolvedor IOs: Claudio Vianna  <claudiolavianna@gmail.com>
#desenvolvedor Android: Roberto Castro  <robocast1331@gmail.com>

version: 0.1.0+1
# Tudo que esta antes do sinal de + é o nome da versão e depois é o código da versão.
#Então aqui o nome para o usuario  é 0.1.0  e o código da versão de controle do app é 1
#Sempre que você der uma atualização para o aplicativo flutter,



environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  path_provider: ^1.2.0
  firebase_core: ^0.4.0+8
  firebase_analytics: ^4.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_sem uso.png"


flutter:

  uses-material-design: true

  assets:
     - assets/images/caderno_lapis.png
     - assets/images/splash.png
     - assets/images/logo.png


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

