name: anote_tudo
description: Faça suas de compras e ou tarefas do dia e salve em seu celular...
#desenvolvedor IOs: Claudio Vianna  <claudiolavianna@gmail.com>
#desenvolvedor Android: Roberto Castro  <robocast1331@gmail.com>

version: 0.1.0+3
# Tudo que esta antes do sinal de + é o nome da versão e depois é o código da versão.
#Então aqui o nome para o usuario  é 0.1.0  e o código da versão de controle do app é 1
#Sempre mudar o código da versão +1 quando fizer atualização para o aplicativo flutter,



environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.6.1
  path_provider: ^1.2.0
  firebase_core: ^0.4.0+8
  firebase_analytics: ^4.0.2
  intro_slider: ^2.2.7
  shared_preferences: ^0.5.3+4
  rflutter_alert: ^1.0.2
  in_app_purchase: ^0.2.1+3




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"


flutter:

  uses-material-design: true

  assets:
     - assets/images/caderno_lapis.png
     - assets/images/splash.png
     - assets/images/flash_nativo.png
     - assets/images/logo.png
     - assets/images/este_seja_bem_vindo.png




  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

